### ISSUE TITLE
update ODI webpage on Alpha

### ISSUE THREAD

**Issue by abquirarte** [cagov/main#1]
**Goal:** Test a new "content type" for organizations. 

**User need:** as a member of the public, I want to learn what ODI is, who is part of it, and what it does. 

**Assumptions:** we assumer that the bare minimum is what people want to know. 

**Current:** https://www.alpha.ca.gov/office-of-digital-innovation/ 

**Timeline** By early February.

**Comment by m-sullivan7** [comment]
Responding to the "help wanted" sign, @abquirarte 😄 

Looks like you want [this page](https://www.alpha.ca.gov/office-of-digital-innovation/) updated. Want me to put drafting this on my list? It'll probably take a round or two of revisions from you to get it right, but I might be able to speed the process up. 😉 

Note for later: page code is found [in this doc](https://github.com/cagov/Alpha/blob/master/src/office-of-digital-innovation/index.html).

**Comment by abquirarte** [comment]
nice catch @m-sullivan7 ! @jpetrucione has copy. for this :) I think we need someone (possibly a dev) to build it out.

**Comment by m-sullivan7** [comment]
Having looked at the page code, depending on what JP's got I might be able to do it now that I've received some schooling from our developers (who would review my work). I'll connect with JP.

Incidentally, this experience might enable me to do the blog build out for the style guide as well.

**Comment by abquirarte** [comment]
amazing!!! thank you @m-sullivan7 !!!!!

**Comment by m-sullivan7** [comment]
Quick update: @jpetrucione is doing another pass on the content and will send it along for another copyedit. Once I've got it, I'll see if it's easy for me to do the updates on alpha.

**Comment by abquirarte** [comment]
sounds good!

**Comment by m-sullivan7** [comment]
First step on this has begun: removing outdated team members.

https://github.com/cagov/Alpha/pull/677

JP has indicated final content will likely come by Friday.

**Comment by m-sullivan7** [comment]
@aaronhans I created a [pull request](https://github.com/cagov/Alpha/pull/679) with the updates @jpetrucione has requested for the ODI page on alpha. I did some hand coding that may or may not have gone well, so we'll definitely need to stage.

JP has asked for a second version to more closely match the [Google Doc](https://docs.google.com/document/u/1/d/1JewxiJDdRxv0WjvGyB7yUEneQEPKWocBj6PCEvBqkwk/edit?usp=gmail_thread&ts=600f4117&gxids=7628) he passed the content to me in. Not represented in that doc is that he'd like to try putting the staff names into columns to shorten the page. I support this, but didn't have the coding savvy to do it. ;)

**Comment by m-sullivan7** [comment]
Second round of edits per @jpetrucione pushed to [staging](https://staging.alpha.technology.ca.gov/office-of-digital-innovation/) via https://github.com/cagov/Alpha/pull/681

**Comment by m-sullivan7** [comment]
Hopefully final pull request before full publication: https://github.com/cagov/Alpha/pull/682

**Comment by m-sullivan7** [comment]
All changes made and content pushed to live.
